### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber":"1000000002",
  "amount": 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber":"1000000002",
  "amount": 100
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "95f89ca457e94dcc93837c8cf9837d75",
  "accountNumber":"1000000002",
  "amount": 20000
}

### query transaction
GET http://localhost:8080/transaction/1a81e0911c134c83b469b4d4cb809a54